cask "oats" do
  # Generated by the release workflow. Do not edit by hand: version comes from
  # RELEASE_TAG, and sha256 comes from the signed DMG that release-publish.sh
  # ships to R2 at desktop/oats.dmg (the same URL below).
  generated_version = "0.15.0"
  generated_sha256 = "00f8de14a0c619e27e1e64d8fecdaadab8a6779a00d9e645fd20ced371b153ed"

  version generated_version
  sha256 generated_sha256

  url "https://pub-dd2807d512d34e55b8a863f675ea8e6e.r2.dev/desktop/oats.dmg",
      verified: "pub-dd2807d512d34e55b8a863f675ea8e6e.r2.dev/desktop/"
  name "Oats"
  desc "AI meeting recorder and notes app"
  homepage "https://ariso.ai/"

  livecheck do
    skip "The release workflow updates this cask after the signed DMG is published"
  end

  depends_on macos: :sonoma

  app "oats.app"
end
