cask "oats" do
  # Generated by the release workflow. Do not edit by hand: version comes from
  # RELEASE_TAG, and sha256 comes from the signed DMG uploaded as oats.dmg.
  generated_version = "0.7.1"
  generated_sha256 = "ef7e1c56e4091b365c722d3ee18651ef5674df0ff4667174b58d7460d6caf832"

  version generated_version
  sha256 generated_sha256

  url "https://github.com/ariso-ai/oats/releases/download/v#{version}/oats.dmg",
      verified: "github.com/ariso-ai/oats/"
  name "Oats"
  desc "AI meeting recorder and notes app"
  homepage "https://ariso.ai/"

  livecheck do
    skip "The release workflow updates this cask after the signed DMG is published"
  end

  depends_on macos: :sonoma

  app "oats.app"
end
