cask "oats" do
  # Generated by the release workflow. Do not edit by hand: version comes from
  # RELEASE_TAG, and sha256 comes from the signed DMG that release-publish.sh
  # ships to R2 at desktop/oats.dmg (the same URL below).
  generated_version = "0.20.0"
  generated_sha256 = "29a65ddab8ae417533be94c4ff9f0ff2d10b301ca213ca87aa1feb995a2d4bd7"

  version generated_version
  sha256 generated_sha256

  url "https://pub-dd2807d512d34e55b8a863f675ea8e6e.r2.dev/desktop/releases/#{generated_version}/oats-#{generated_sha256}.dmg",
      verified: "pub-dd2807d512d34e55b8a863f675ea8e6e.r2.dev/desktop/releases/"
  name "Oats"
  desc "AI meeting recorder and notes app"
  homepage "https://ariso.ai/"

  livecheck do
    skip "The release workflow updates this cask after the signed DMG is published"
  end

  depends_on macos: :sonoma

  app "oats.app"
end
