/**
 * Which model generates meeting notes on the Local backend.
 *
 * Today the registry holds exactly one entry — the on-device Gemma that
 * `model_manager.rs` already downloads and `transcribe.rs::run_notes` already
 * runs. The `remote` variant exists so the picker, the persisted setting, and
 * the parser are shaped for the OpenAI/Gemini/Anthropic options that land in a
 * later increment; no remote model is registered yet, so `parseNotesModel`
 * rejects every one of them.
 *
 * See docs/superpowers/specs/2026-09-19-local-notes-model-picker-design.md.
 */
export type RemoteProvider = 'openai' | 'gemini' | 'anthropic';

export type NotesModelId =
  | { kind: 'local'; id: string }
  | { kind: 'remote'; provider: RemoteProvider; id: string };

export interface NotesModelOption {
  value: NotesModelId;
  label: string;
}

/** The model notes have always been generated by — a zero-download default. */
export const DEFAULT_NOTES_MODEL: NotesModelId = {
  kind: 'local',
  id: 'gemma-3-1b-it-qat-4bit',
};

/**
 * Every model the picker offers, in display order. This is a fixed list, not
 * free text: the selected id reaches a model directory path (and, later, a
 * provider URL), so only ids registered here may ever be persisted.
 */
export const NOTES_MODEL_OPTIONS: NotesModelOption[] = [
  { value: DEFAULT_NOTES_MODEL, label: 'Gemma 3 1B' },
];

/** A stable identity for a selection — safe as a `v-for` key and for equality. */
export function notesModelKey(model: NotesModelId): string {
  return model.kind === 'local' ? `local:${model.id}` : `remote:${model.provider}:${model.id}`;
}

/** The registry's display name, falling back to the bare id if unregistered. */
export function notesModelLabel(model: NotesModelId): string {
  const key = notesModelKey(model);
  const option = NOTES_MODEL_OPTIONS.find((o) => notesModelKey(o.value) === key);
  return option ? option.label : model.id;
}

/**
 * Coerce a persisted `settings.json` value into a registered model. Anything
 * absent, malformed, or naming a model this build does not ship falls back to
 * the default rather than being trusted.
 */
export function parseNotesModel(raw: unknown): NotesModelId {
  if (typeof raw !== 'object' || raw === null) return DEFAULT_NOTES_MODEL;
  const candidate = raw as Partial<NotesModelId> & { provider?: unknown };
  if (typeof candidate.kind !== 'string' || typeof candidate.id !== 'string') {
    return DEFAULT_NOTES_MODEL;
  }
  const match = NOTES_MODEL_OPTIONS.find(
    (o) => notesModelKey(o.value) === notesModelKey(candidate as NotesModelId),
  );
  return match ? match.value : DEFAULT_NOTES_MODEL;
}
