/**
 * Which model generates meeting notes on the Local backend.
 *
 * On-device entries run through `model_manager.rs` / `transcribe.rs::run_notes`
 * and cost nothing but disk. Remote entries call a provider's API with a key
 * the user supplies, which the Rust `credentials` module keeps in the OS
 * keychain — so a remote entry is pickable only once its provider is connected.
 *
 * See docs/superpowers/specs/2026-09-19-local-notes-model-picker-design.md.
 */
export type RemoteProvider = 'openai' | 'gemini' | 'anthropic';

/** Every provider a key can be stored for, in display order. Mirrors the Rust
 *  `RemoteProvider::ALL` — both sides must agree on these wire names. */
export const REMOTE_PROVIDERS: RemoteProvider[] = ['openai', 'gemini', 'anthropic'];

const REMOTE_PROVIDER_LABELS: Record<RemoteProvider, string> = {
  openai: 'OpenAI',
  gemini: 'Google Gemini',
  anthropic: 'Anthropic',
};

/** The provider's own name, for the key prompt and the disclosure line. */
export function remoteProviderLabel(provider: RemoteProvider): string {
  return REMOTE_PROVIDER_LABELS[provider];
}

export type NotesModelId =
  | { kind: 'local'; id: string }
  | { kind: 'remote'; provider: RemoteProvider; id: string };

export interface NotesModelOption {
  value: NotesModelId;
  label: string;
}

/** The model notes have always been generated by — a zero-download default. */
export const DEFAULT_NOTES_MODEL: NotesModelId = {
  kind: 'local',
  id: 'gemma-3-1b-it-qat-4bit',
};

/**
 * Every model the picker offers, in display order. This is a fixed list, not
 * free text: the selected id reaches a model directory path (and, later, a
 * provider URL), so only ids registered here may ever be persisted.
 */
export const NOTES_MODEL_OPTIONS: NotesModelOption[] = [
  { value: DEFAULT_NOTES_MODEL, label: 'Gemma 3 1B' },
  { value: { kind: 'remote', provider: 'openai', id: 'gpt-5.1' }, label: 'GPT-5.1' },
  { value: { kind: 'remote', provider: 'openai', id: 'gpt-5.1-mini' }, label: 'GPT-5.1 mini' },
  {
    value: { kind: 'remote', provider: 'gemini', id: 'gemini-3.0-flash' },
    label: 'Gemini 3.0 Flash',
  },
  {
    value: { kind: 'remote', provider: 'gemini', id: 'gemini-3.5-flash' },
    label: 'Gemini 3.5 Flash',
  },
  {
    value: { kind: 'remote', provider: 'gemini', id: 'gemini-3.7-flash' },
    label: 'Gemini 3.7 Flash',
  },
  {
    value: { kind: 'remote', provider: 'anthropic', id: 'claude-haiku-4-5' },
    label: 'Claude Haiku 4.5',
  },
  {
    value: { kind: 'remote', provider: 'anthropic', id: 'claude-sonnet-5' },
    label: 'Claude Sonnet 5',
  },
];

/** A stable identity for a selection — safe as a `v-for` key and for equality. */
export function notesModelKey(model: NotesModelId): string {
  return model.kind === 'local' ? `local:${model.id}` : `remote:${model.provider}:${model.id}`;
}

/** The registry's display name, falling back to the bare id if unregistered. */
export function notesModelLabel(model: NotesModelId): string {
  const key = notesModelKey(model);
  const option = NOTES_MODEL_OPTIONS.find((o) => notesModelKey(o.value) === key);
  return option ? option.label : model.id;
}

/**
 * Coerce a persisted `settings.json` value into a registered model. Anything
 * absent, malformed, or naming a model this build does not ship falls back to
 * the default rather than being trusted.
 */
export function parseNotesModel(raw: unknown): NotesModelId {
  if (typeof raw !== 'object' || raw === null) return DEFAULT_NOTES_MODEL;
  const candidate = raw as Partial<NotesModelId> & { provider?: unknown };
  if (typeof candidate.kind !== 'string' || typeof candidate.id !== 'string') {
    return DEFAULT_NOTES_MODEL;
  }
  const match = NOTES_MODEL_OPTIONS.find(
    (o) => notesModelKey(o.value) === notesModelKey(candidate as NotesModelId),
  );
  return match ? match.value : DEFAULT_NOTES_MODEL;
}
